### ISSUE TITLE
Creating bindings for libwinit

### ISSUE THREAD

**Issue by VarLad** [JuliaInterop/Clang.jl#412] opened 2022-12-20 17:11 UTC
Apparently, Clang.jl errors when translating this bit of code:
```c
#include <stdint.h>

enum X {
  A,
  B,
  C,
};
typedef uint32_t X;
```

The error is:

```
ERROR: LoadError: AssertionError: ptr_ref[] != C_NULL
Stacktrace:
 [1] Clang.TokenList(tu::Ptr{Clang.LibClang.CXTranslationUnitImpl}, sr::Clang.LibClang.CXSourceRange)
   @ Clang ~/.julia/packages/Clang/HZdsi/src/token.jl:13
 [2] tokenize(c::Clang.CLNoDeclFound)
   @ Clang ~/.julia/packages/Clang/HZdsi/src/token.jl:105
 [3] is_same(cursor1::Clang.CLNoDeclFound, cursor2::Clang.CLEnumDecl)
   @ Clang.Generators ~/.julia/packages/Clang/HZdsi/src/generator/utils.jl:19
 [4] sanity_check(dag::ExprDAG, options::Dict{String, Any})
   @ Clang.Generators ~/.julia/packages/Clang/HZdsi/src/generator/audit.jl:68
 [5] (::Audit)(dag::ExprDAG, options::Dict{String, Any})
   @ Clang.Generators ~/.julia/packages/Clang/HZdsi/src/generator/passes.jl:859
 [6] build!(ctx::Context, stage::Clang.Generators.BuildStage)
   @ Clang.Generators ~/.julia/packages/Clang/HZdsi/src/generator/context.jl:169
 [7] build!(ctx::Context)
   @ Clang.Generators ~/.julia/packages/Clang/HZdsi/src/generator/context.jl:160
 [8] top-level scope
   @ ~/generator.jl:8
   ```
   
   This is technically valid C code.

**Comment by VarLad** [comment] 2022-12-20 18:02
@Gnimuc Is to possible to translate the above to to 
```julia
@cenum X::UInt32 begin
     A,
     B,
     C
end
```
using Clang.jl (using generator.toml)?

**Comment by Gnimuc** [comment] 2022-12-20 23:02
> This is technically valid C code.

you set the bar too low. 

the code below is also valid C code, but I believe you can not translate it elegant to any other main stream languages without implementing the insane namespace machanisim of C.

```c
typedef struct A {
  int x;
} B;

typedef struct B {
  int x;
} A;
```

however, you should not get this error/crash. the expected behavior is that the generator yields above statement as error logs.

**Comment by VarLad** [comment] 2022-12-20 23:29
@Gnimuc C doesn't have a way to deal with the alternative of something like:

```julia
@cenum Name::UInt32 begin
     Param
end
```

Languages like Rust, (when exporting to C headers via some autogen tool), do

``` c
enum Name {
  Param
};
typedef uint32_t X;
```
to convey the above.

Does it make sense for a feature request to have an optional parameter (false by default) in generator.toml to accept the above code and translate it to appropriate Julia code? I can try looking into making a PR as well!

**Comment by Gnimuc** [comment] 2022-12-21 01:18
I would suggest the following pattern:

```c
enum {
  A,
  B,
  C
}; 

// the purpose here is to prevent users in any way from using C's mysterious enum types.

typedef int name;
```

but I'm always open for PRs.

**Comment by VarLad** [comment] 2022-12-21 09:47
We can have both patterns. :)
Can you point me to the file I need to look into to make this change?

**Comment by Gnimuc** [comment] 2022-12-21 09:54
https://github.com/JuliaInterop/Clang.jl/issues/412#issuecomment-1360637892 is already supported. 

[This pattern](https://github.com/JuliaInterop/Clang.jl/issues/412#issuecomment-1360464205) violates the assumption used for merging translation units, so you probably need to check [all down-stream passes](https://github.com/JuliaInterop/Clang.jl/blob/d49d1fcb132c737f6c3c3104031e0276b25d09c9/src/generator/context.jl#L95-L105).

**Comment by Gnimuc** [comment] 2022-12-21 10:42
I fixed the issue in the OP: `AssertionError: ptr_ref[] != C_NULL`

You can checkout the master branch and give it a test.

**Comment by Gnimuc** [comment] 2022-12-21 10:58
I also added a ["no audit"](https://github.com/JuliaInterop/Clang.jl/commit/14a90e96abdcbbc93e24f2cff0b4c29b986b4f2a) config entry to make it easy to work around these kinda problems.

**Comment by Gnimuc** [comment] 2022-12-22 11:43
The pattern seems to be:

1. Given a typedef identifier,
2. If the underlying type is integer(how to make such a list of integer types?) 
3. Then check whether there is an enum tag with the same name (and this node should not be marked as `Skip`)
4. If , mark the typedef node as `Skip` and replace the tag node with the newly inserted id

**Closed** 2023-01-02 06:07 UTC

**Comment by VarLad** [comment] 2023-03-10 17:52
> I would suggest the following pattern:
> 
> ```c
> enum {
>   A,
>   B,
>   C
> }; 
> 
> // the purpose here is to prevent users in any way from using C's mysterious enum types.
> 
> typedef int name;
> ```
> 
> but I'm always open for PRs.

@Gnimuc I tried this, it generates:
```
@cenum var"##Ctag#293"::UInt32 begin
    A = 0
    B = 1
    C = 2
end

const name = Cint
```
I'm not sure how to use this. Would it be possible to deanonymize this like we have for structs?
I've opened an issue here: https://github.com/JuliaInterop/Clang.jl/issues/420

**Comment by Gnimuc** [comment] 2023-03-11 02:21
@VarLad I actually implemented https://github.com/JuliaInterop/Clang.jl/pull/413/files for you. Have you tried that?
